title:                  "Bootstrap"
baseURL:                "https://getbootstrap.kr"

docsDir:                "site"

subtitle:               "세계에서 가장 인기있는 HTML, CSS, JS 라이브러리."
description:            "강력하고 확장 가능하며 기능이 풍부한 프론트엔드 툴킷. Sass로 빌드 및 커스터마이징하고, 사전 빌드된 그리드 시스템 및 구성 요소를 활용하고, 강력한 JavaScript 플러그인으로 프로젝트에 생기를 불어넣습니다."
authors:                "Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들"

current_version:        "5.3.6"
current_ruby_version:   "5.3.6"
docs_version:           "5.3"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/twbs"
repo:                   "https://github.com/twbs/bootstrap"
x:                      "getbootstrap"
opencollective:         "https://opencollective.com/bootstrap"
blog:                   "https://blog.getbootstrap.com/"
themes:                 "https://themes.getbootstrap.com/"
icons:                  "https://icons.getbootstrap.kr/"
swag:                   "https://cottonbureau.com/people/bootstrap"

arumduri:               "https://github.com/arumduri/bootstrap"

analytics:
  fathom_site:          "ITUSEYJG"
  ga_site:              ""

algolia:
  app_id:                "40ZRL3P9Q5"
  api_key:               "1423f47ec4e6e0793aeebfb72e2fcc04"
  index_name:            "bootstrap-kr"

download:
  source:               "https://github.com/twbs/bootstrap/archive/v5.3.6.zip"
  dist:                 "https://github.com/twbs/bootstrap/releases/download/v5.3.6/bootstrap-5.3.6-dist.zip"
  dist_examples:        "https://github.com/twbs/bootstrap/releases/download/v5.3.6/bootstrap-5.3.6-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
  css_hash:             "sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
  css_rtl:              "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.rtl.min.css"
  css_rtl_hash:         "sha384-MdqCcafa5BLgxBDJ3d/4D292geNL64JyRtSGjEszRUQX9rhL1QkcnId+OT7Yw+D+"
  js:                   "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js"
  js_hash:              "sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D"
  js_bundle:            "https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
  js_bundle_hash:       "sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
  popper:               "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  popper_hash:          "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
