files:
  - source: /site/content/docs/**/*.md
    ignore:
      - /site/content/docs/versions.md
      - /site/content/docs/*/examples
    translation: /site/content_%two_letters_code%/docs/**/%original_file_name%
    type: fm_md
